"""add feedback fields to chat_messages

Revision ID: 2c2b9ab5dc03
Revises: 001
Create Date: 2026-03-26 13:35:34.681486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2b9ab5dc03'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('feedback', sa.String(length=10), nullable=True))
    op.add_column('chat_messages', sa.Column('feedback_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'feedback_at')
    op.drop_column('chat_messages', 'feedback')
    # ### end Alembic commands ###
